### ISSUE TITLE
Errors in the Swift tutorial (Chapter 1)

### ISSUE THREAD

**Issue by kaikoveritch** [cui-unige/swift#1]
1) In the "Optionals" section, the comment (below) is wrong since trainer1 is initialized:
`var trainer1: String? = "Ash"`
`// trainer1: String? = nil`

2) In the "Arrays" section, it would be important to specify that ArraySlice is a different type from Array, and that a slice keeps the original indexes from the Array. Also the "append()" function and array addition are not mentioned. Finally only 1 way to create empty arrays is shown, it could be interesting to add the other methods.

3) In the "Dictionaries" section, a dictionary is declared as a constant and then modified here:
`enum SpeciesType { case grass, fire, water }`
`let speciesTypes = ["Bulbasaur": SpeciesType.grass, "Charmander": SpeciesType.fire]`
`speciesTypes["Bulbasaur"] = .water`
and here:
`enum SpeciesType { case grass, fire, water }`
`let speciesTypes = ["Bulbasaur": SpeciesType.grass, "Charmander": SpeciesType.fire]`
`speciesTypes["Oddish"] = .grass`
`speciesTypes["Charmander"] = nil`

**Comment by kyouko-taiga** [comment]
Points 1 and 3 are fixed in 3ee42cf90b9a1183f65edba66b99a87629cdc13f

Although relevant, I think the point 2 shouldn't be addressed in chapter 1. The role of this chapter isn't to make a comprehensive introduction to Swift's `Collection` (whose conformance feed almost all the methods of `Array`). I plan on adding an 8th chapter on those kinds of protocol (`Collection`, `Sequence`, `IteratorProtocol`, ...) with their conformances. When that'll be done, I'll make a forward link in chapter 1.
